import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "node:module";
import { execFileSync } from "node:child_process";

const banner = `/*
Handwriting: pen ink on ordinary Markdown notes in Obsidian.
Generated by esbuild. The source lives in src/.
*/`;

const prod = process.argv[2] === "production";

function git(args) {
	try {
		return execFileSync("git", args, { encoding: "utf8" }).trim();
	} catch {
		return "unverified";
	}
}

const sourceCommit = prod ? git(["rev-parse", "HEAD"]) : "unverified";
const sourceTree = prod ? git(["rev-parse", "HEAD^{tree}"]) : "unverified";
const dirtyStatus = prod ? (git(["status", "--porcelain"]) === "" ? "clean" : "dirty") : "unverified";
const verified = prod && sourceCommit !== "unverified" && sourceTree !== "unverified" && dirtyStatus === "clean";

const ctx = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	define: {
		__HW_BUILD_SOURCE_COMMIT__: JSON.stringify(sourceCommit),
		__HW_BUILD_SOURCE_TREE__: JSON.stringify(sourceTree),
		__HW_BUILD_DIRTY_STATUS__: JSON.stringify(dirtyStatus),
		__HW_BUILD_VERIFIED__: JSON.stringify(verified),
	},
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await ctx.rebuild();
	process.exit(0);
} else {
	await ctx.watch();
}
